<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MetricianLibraryFrameworks)</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Metrician.Core.Graph\Metrician.Core.Graph.csproj" />
    <ProjectReference Include="..\Metrician.Contracts.Renderables\Metrician.Contracts.Renderables.csproj" />
  </ItemGroup>

</Project>
